name: Publish the paper

on: [push, workflow_dispatch]

jobs:
  build-paper:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - uses: pandoc/actions/setup@main
      with:
        version: 2.19
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          paper:
          - 'paper.ipynb'
    - name: build the paper
      if: steps.filter.outputs.paper == 'true'
      run: ./build-site.sh
      shell: bash
